# Generated by Django 5.1.6 on 2025-03-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_player_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="game",
        ),
        migrations.AddField(
            model_name="game",
            name="game",
            field=models.ManyToManyField(related_name="players", to="game.player"),
        ),
    ]
