# Generated by Django 5.1.6 on 2025-03-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_remove_player_game_game_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="game",
        ),
        migrations.AddField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(related_name="games", to="game.player"),
        ),
    ]
