# Generated by Django 5.1.6 on 2025-03-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_remove_game_game_game_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="code",
            field=models.CharField(
                default=None, editable=False, max_length=6, unique=True
            ),
        ),
    ]
