# Generated by Django 5.1.6 on 2025-03-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_game_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
