# Generated by Django 5.1.6 on 2025-03-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_game_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="last_updated",
        ),
    ]
